### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by kaszageri** [Skyler-X670/SKYLER-FPS#1]
**Clown Obfuscation**
Take it down idc:
https://ghostbin.co/paste/xmc7

**Comment by kaszageri** [comment]
https://pastebin.com/AR7W3YL0 backup

**Comment by Skyler-X670** [comment]
Oh thanks dude
I appreciate that

Pada tanggal Min, 16 Mei 2021 02.56, kaszageri ***@***.***>
menulis:
